spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  application.name: account
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server.port: 8080

springdoc:
  packagesToScan: com.modsen.account
  api-docs:
    enabled: true
    path: /v3/api-docs/account
  swagger-ui:
    path: /v3/api-docs/account
