spring:
  application.name: gateway
  main:
    web-application-type: reactive
  cloud.gateway:
    discovery:
      locator:
        enabled: true
    routes:
      - id: account
        uri: lb://account
        predicates:
          - Path=/users/**,/v3/api-docs/account
        filters:
          - AuthenticationFilter
          - RewritePath=/account/(?<path>.*), /$\{path}
      - id: eureka-api
        uri: http://${app.eureka-server}:8761
        predicates:
          - Path=/eureka/api/{segment}
        filters:
          - SetPath=/eureka/{segment}
      - id: eureka-web-start
        uri: http://${app.eureka-server}:8761
        predicates:
          - Path=/eureka/web
        filters:
          - SetPath=/
      - id: eureka-web-other
        uri: http://${app.eureka-server}:8761
        predicates:
          - Path=/eureka/**
      - id: book
        uri: lb://book
        predicates:
          - Path=/books/**,/libraries/**,/v3/api-docs/book
        filters:
          - AuthenticationFilter
          - RewritePath=/book/(?<path>.*), /$\{path}
      - id: registration
        uri: lb://registration
        predicates:
          - Path=/auth/**,/v3/api-docs/registration
        filters:
          - AuthenticationFilter
          - RewritePath=/registration/(?<path>.*), /$\{path}
      - id: config-server
        uri: ${spring.cloud.config.uri}
        predicates:
          - Path=/config/**
        filters:
          - RewritePath=/config-server/(?<segment>.*), /$\{segment}

server:
  port: 8080

app.eureka-server: discovery
app.config.server: config-server

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /v3/api-docs/${server.servlet.contextPath}
    urls:
      - name: account
        url: /v3/api-docs/account
      - name: registration
        url: /v3/api-docs/registration
      - name: book
        url: /v3/api-docs/book

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
