management.endpoints.web.exposure.include: "*"

spring:
  config.import: "configserver:"
  application.name: discovery
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://config-server:8888
    username: ${CONFIG_SERVER_USR}
    password: ${CONFIG_SERVER_PWD}